name: Build WF
on:
  push:
    branches: 
      - main
permissions:
  contents: read
jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Maven Build
        run: mvn install
      - name: upload artifact(WAR)
        uses: actions/upload-artifact@v4
        with: 
          name: vprofile-project
          path: taget/*.WAR
      - name: Notify if build faiure
        if: faiure()
        run: echo "Build failed . check logs"

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Maven Testing
        run: mvn test 
      - name: Maven checkstyle
        run: mvn checkstyle:checkstyle
        
        

