name: vprofile cicd wf
on:
   push:
     branches: 
       - main
   pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Maven Build
        run: mvn install
      - name: upload artifact(WAR)
        uses: actions/upload-artifact@v4
        with: 
          name: vprofile-project
          path: taget/*.WAR
      - name: Notify if build faiure
        if: failure()
        run: echo "Build failed . check logs"

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Maven Testing
        if: github.ref == 'refs/heads/main'
        run: mvn test 
      - name: Maven checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle
      - name: Run tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping unit tests and code analysis"
  Security_scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Run Trivy filesystem Security scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: json
          exit-code: 0
          vuln-type: os,library
          output: trivy-results.json
      - name: Upload trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: vprofile-app
          path: trivy-results.json
        

