name: vprofile cicd wf
on:
   push:
     branches: 
       - main
   pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Maven Build
        run: mvn install
      - name: upload artifact(WAR)
        uses: actions/upload-artifact@v4
        with: 
          name: vprofile-project
          path: target/*.war
      - name: Notify if build faiure
        if: failure()
        run: echo "Build failed . check logs"

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Maven Testing
        if: github.ref == 'refs/heads/main'
        run: mvn test 
      - name: Maven checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:checkstyle
      - name: Run tests on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Skipping unit tests and code analysis"
  Security_scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Trivy filesystem Security scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: json
          exit-code: 0
          vuln-type: os,library
          output: trivy-results.json
      - name: Upload trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: trivy-scan-results
          path: trivy-results.json
  BUILD_AND_PUBLISH:
    runs-on: ubuntu-latest
    needs: [ Build, Testing, Security_scan ]
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Login to Docker Hub
        id: login-dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Docker-files/app/multistage/Dockerfile -t $DOCKER_HUB_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG .
          
          docker push $DOCKER_HUB_USERNAME/$DOCKER_REPOSITORY:$IMAGE_TAG
            

        

