name: Build WF
on:
  push:
    branches: 
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Maven Build
        uses: mvn install
  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Maven Testing
        uses: mvn test 
      - name: Maven checkstyle
        uses: mvn checkstyle:checkstyle
        
        

